-- Script DDL - Sistema Gerenciador de Musicas (PostgreSQL)
-- Reune a estrutura das migrations Flyway num arquivo so, pra entrega.


-- =====================================================================
-- V1 - criar tabela usuario
-- =====================================================================
CREATE TABLE IF NOT EXISTS usuario (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    nome VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    senha VARCHAR(255) NOT NULL,
    role VARCHAR(255) NOT NULL,

    CONSTRAINT pk_usuario PRIMARY KEY (id),
    CONSTRAINT uk_usuario_email UNIQUE (email),
    CONSTRAINT ck_usuario_role CHECK (role IN ('ADMIN', 'USER'))
);


-- =====================================================================
-- V2 - criar catalogo musical (artista, album, genero, musica)
-- =====================================================================
CREATE TABLE IF NOT EXISTS artista (
    id_artista BIGINT GENERATED BY DEFAULT AS IDENTITY,
    nome VARCHAR(255) NOT NULL,
    descricao TEXT,
    foto_perfil_url VARCHAR(2048),

    CONSTRAINT pk_artista
        PRIMARY KEY (id_artista)
);


CREATE TABLE IF NOT EXISTS album (
    id_album BIGINT GENERATED BY DEFAULT AS IDENTITY,
    id_artista BIGINT NOT NULL,
    titulo VARCHAR(255) NOT NULL,
    ano_lancamento SMALLINT NOT NULL,
    capa_url VARCHAR(2048),

    CONSTRAINT pk_album
        PRIMARY KEY (id_album),

    CONSTRAINT fk_album_artista
        FOREIGN KEY (id_artista)
        REFERENCES artista (id_artista),

    CONSTRAINT ck_album_ano
        CHECK (ano_lancamento BETWEEN 1800 AND 2100),

    CONSTRAINT ck_album_titulo_nao_vazio
        CHECK (BTRIM(titulo) <> '')
);

CREATE UNIQUE INDEX uk_album_artista_titulo_ano_ci
    ON album (
        id_artista,
        LOWER(BTRIM(titulo)),
        ano_lancamento
    );


CREATE TABLE IF NOT EXISTS genero (
    id_genero BIGINT GENERATED BY DEFAULT AS IDENTITY,
    nome VARCHAR(100) NOT NULL,

    CONSTRAINT pk_genero
        PRIMARY KEY (id_genero),

    CONSTRAINT uk_genero_nome
        UNIQUE (nome)
);


CREATE TABLE musica (
    id_musica BIGINT GENERATED BY DEFAULT AS IDENTITY,
    id_album BIGINT,
    titulo VARCHAR(255) NOT NULL,
    letra TEXT,
    duracao_segundos INTEGER NOT NULL,
    ano_lancamento SMALLINT NOT NULL,

    CONSTRAINT pk_musica
        PRIMARY KEY (id_musica),

    CONSTRAINT fk_musica_album
        FOREIGN KEY (id_album)
        REFERENCES album (id_album),

    CONSTRAINT ck_musica_duracao
        CHECK (duracao_segundos > 0),

    CONSTRAINT ck_musica_ano
        CHECK (ano_lancamento BETWEEN 1800 AND 2100)
);


CREATE TABLE IF NOT EXISTS musica_artista (
    id_musica BIGINT NOT NULL,
    id_artista BIGINT NOT NULL,

    CONSTRAINT pk_musica_artista
        PRIMARY KEY (id_musica, id_artista),

    CONSTRAINT fk_musica_artista_musica
        FOREIGN KEY (id_musica)
        REFERENCES musica (id_musica)
        ON DELETE CASCADE,

    CONSTRAINT fk_musica_artista_artista
        FOREIGN KEY (id_artista)
        REFERENCES artista (id_artista)
        ON DELETE CASCADE
);


CREATE TABLE IF NOT EXISTS musica_genero (
    id_musica BIGINT NOT NULL,
    id_genero BIGINT NOT NULL,

    CONSTRAINT pk_musica_genero
        PRIMARY KEY (id_musica, id_genero),

    CONSTRAINT fk_musica_genero_musica
        FOREIGN KEY (id_musica)
        REFERENCES musica (id_musica)
        ON DELETE CASCADE,

    CONSTRAINT fk_musica_genero_genero
        FOREIGN KEY (id_genero)
        REFERENCES genero (id_genero)
        ON DELETE CASCADE
);


-- =====================================================================
-- V3 - criar tabelas playlist (playlist, playlist_musica)
-- =====================================================================
CREATE TABLE IF NOT EXISTS playlist (
    id_playlist BIGINT GENERATED BY DEFAULT AS IDENTITY,
    nome VARCHAR(255) NOT NULL,
    descricao TEXT,
    id_usuario BIGINT NOT NULL,
    data_criacao TIMESTAMP WITH TIME ZONE
        NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT pk_playlist
        PRIMARY KEY (id_playlist),

    CONSTRAINT fk_playlist_usuario
        FOREIGN KEY (id_usuario)
        REFERENCES usuario (id)
        ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS playlist_musica (
    id_playlist BIGINT NOT NULL,
    id_musica BIGINT NOT NULL,

    CONSTRAINT pk_playlist_musica
        PRIMARY KEY (id_playlist, id_musica),

    CONSTRAINT fk_playlist_musica_playlist
        FOREIGN KEY (id_playlist)
        REFERENCES playlist (id_playlist)
        ON DELETE CASCADE,

    CONSTRAINT fk_playlist_musica_musica
        FOREIGN KEY (id_musica)
        REFERENCES musica (id_musica)
        ON DELETE CASCADE
);


-- =====================================================================
-- V4 - adicionar artista principal (id_artista) em musica
-- =====================================================================
ALTER TABLE musica
    ADD COLUMN id_artista BIGINT;

ALTER TABLE musica
    ADD CONSTRAINT fk_musica_artista_principal
        FOREIGN KEY (id_artista)
        REFERENCES artista (id_artista);

ALTER TABLE musica
    ALTER COLUMN id_artista SET NOT NULL;


-- =====================================================================
-- V5 - criar tabela perfil
-- =====================================================================
CREATE TABLE perfil (
    id_perfil BIGINT GENERATED BY DEFAULT AS IDENTITY,
    id_usuario BIGINT NOT NULL,

    foto_url VARCHAR(2048),
    banner_url VARCHAR(2048),
    biografia TEXT,
    frase_destaque VARCHAR(500),

    id_artista_destaque BIGINT,
    id_album_destaque BIGINT,
    id_musica_destaque BIGINT,
    tipo_destaque_principal VARCHAR(20),

    CONSTRAINT pk_perfil
        PRIMARY KEY (id_perfil),

    CONSTRAINT uk_perfil_usuario
        UNIQUE (id_usuario),

    CONSTRAINT fk_perfil_usuario
        FOREIGN KEY (id_usuario)
        REFERENCES usuario (id)
        ON DELETE CASCADE,

    CONSTRAINT fk_perfil_artista_destaque
        FOREIGN KEY (id_artista_destaque)
        REFERENCES artista (id_artista)
        ON DELETE SET NULL,

    CONSTRAINT fk_perfil_album_destaque
        FOREIGN KEY (id_album_destaque)
        REFERENCES album (id_album)
        ON DELETE SET NULL,

    CONSTRAINT fk_perfil_musica_destaque
        FOREIGN KEY (id_musica_destaque)
        REFERENCES musica (id_musica)
        ON DELETE SET NULL,

    CONSTRAINT ck_perfil_tipo_destaque_principal
        CHECK (
            tipo_destaque_principal IS NULL
            OR tipo_destaque_principal IN ('ARTISTA', 'MUSICA', 'ALBUM')
        )
);

CREATE INDEX idx_perfil_artista_destaque
    ON perfil (id_artista_destaque);

CREATE INDEX idx_perfil_album_destaque
    ON perfil (id_album_destaque);

CREATE INDEX idx_perfil_musica_destaque
    ON perfil (id_musica_destaque);


-- =====================================================================
-- V6 - criar tabela review
-- V23 - permitir review de álbum (id_musica passa a ser opcional)
-- =====================================================================
CREATE TABLE review (
    id_review BIGINT GENERATED BY DEFAULT AS IDENTITY,
    id_usuario BIGINT NOT NULL,
    id_musica BIGINT,
    id_album BIGINT,
    nota SMALLINT NOT NULL,
    texto TEXT,
    criada_em TIMESTAMP WITH TIME ZONE
        NOT NULL DEFAULT CURRENT_TIMESTAMP,
    atualizada_em TIMESTAMP WITH TIME ZONE
        NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT pk_review
        PRIMARY KEY (id_review),

    CONSTRAINT fk_review_usuario
        FOREIGN KEY (id_usuario)
        REFERENCES usuario (id)
        ON DELETE CASCADE,

    CONSTRAINT fk_review_musica
        FOREIGN KEY (id_musica)
        REFERENCES musica (id_musica)
        ON DELETE CASCADE,

    CONSTRAINT fk_review_album
        FOREIGN KEY (id_album)
        REFERENCES album (id_album)
        ON DELETE CASCADE,

    CONSTRAINT uk_review_usuario_musica
        UNIQUE (id_usuario, id_musica),

    CONSTRAINT uk_review_usuario_album
        UNIQUE (id_usuario, id_album),

    CONSTRAINT ck_review_nota
        CHECK (nota BETWEEN 1 AND 5),

    CONSTRAINT ck_review_texto
        CHECK (texto IS NULL OR BTRIM(texto) <> ''),

    -- Toda review é de exatamente um alvo: uma música OU um álbum.
    CONSTRAINT ck_review_alvo
        CHECK (
            (id_musica IS NOT NULL AND id_album IS NULL)
            OR (id_musica IS NULL AND id_album IS NOT NULL)
        )
);

CREATE INDEX idx_review_musica
    ON review (id_musica);

CREATE INDEX idx_review_album
    ON review (id_album);

CREATE INDEX idx_review_usuario
    ON review (id_usuario);

CREATE OR REPLACE FUNCTION fn_atualizar_data_review()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
    NEW.atualizada_em = CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$;

CREATE TRIGGER trg_atualizar_data_review
BEFORE UPDATE ON review
FOR EACH ROW
EXECUTE FUNCTION fn_atualizar_data_review();


-- =====================================================================
-- V7 - criar tabelas de seguidores
-- =====================================================================
CREATE TABLE usuario_segue_usuario (
    id_seguidor BIGINT NOT NULL,
    id_seguido BIGINT NOT NULL,
    seguido_em TIMESTAMP WITH TIME ZONE
        NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT pk_usuario_segue_usuario
        PRIMARY KEY (id_seguidor, id_seguido),

    CONSTRAINT fk_usuario_segue_usuario_seguidor
        FOREIGN KEY (id_seguidor)
        REFERENCES usuario (id)
        ON DELETE CASCADE,

    CONSTRAINT fk_usuario_segue_usuario_seguido
        FOREIGN KEY (id_seguido)
        REFERENCES usuario (id)
        ON DELETE CASCADE,

    CONSTRAINT ck_usuario_nao_segue_si_mesmo
        CHECK (id_seguidor <> id_seguido)
);

CREATE INDEX idx_usuario_segue_usuario_seguido
    ON usuario_segue_usuario (id_seguido);


CREATE TABLE usuario_segue_artista (
    id_usuario BIGINT NOT NULL,
    id_artista BIGINT NOT NULL,
    seguido_em TIMESTAMP WITH TIME ZONE
        NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT pk_usuario_segue_artista
        PRIMARY KEY (id_usuario, id_artista),

    CONSTRAINT fk_usuario_segue_artista_usuario
        FOREIGN KEY (id_usuario)
        REFERENCES usuario (id)
        ON DELETE CASCADE,

    CONSTRAINT fk_usuario_segue_artista_artista
        FOREIGN KEY (id_artista)
        REFERENCES artista (id_artista)
        ON DELETE CASCADE
);

CREATE INDEX idx_usuario_segue_artista_artista
    ON usuario_segue_artista (id_artista);


-- =====================================================================
-- V8 - criar curtidas e reproducoes
-- =====================================================================
CREATE TABLE curtida_musica (
    id_usuario BIGINT NOT NULL,
    id_musica BIGINT NOT NULL,
    curtida_em TIMESTAMP WITH TIME ZONE
        NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT pk_curtida_musica
        PRIMARY KEY (id_usuario, id_musica),

    CONSTRAINT fk_curtida_musica_usuario
        FOREIGN KEY (id_usuario)
        REFERENCES usuario (id)
        ON DELETE CASCADE,

    CONSTRAINT fk_curtida_musica_musica
        FOREIGN KEY (id_musica)
        REFERENCES musica (id_musica)
        ON DELETE CASCADE
);

CREATE INDEX idx_curtida_musica_musica
    ON curtida_musica (id_musica);


CREATE TABLE reproducao (
    id_reproducao BIGINT GENERATED BY DEFAULT AS IDENTITY,
    id_usuario BIGINT NOT NULL,
    id_musica BIGINT NOT NULL,
    reproduzida_em TIMESTAMP WITH TIME ZONE
        NOT NULL DEFAULT CURRENT_TIMESTAMP,
    segundos_ouvidos INTEGER NOT NULL,

    CONSTRAINT pk_reproducao
        PRIMARY KEY (id_reproducao),

    CONSTRAINT fk_reproducao_usuario
        FOREIGN KEY (id_usuario)
        REFERENCES usuario (id)
        ON DELETE CASCADE,

    CONSTRAINT fk_reproducao_musica
        FOREIGN KEY (id_musica)
        REFERENCES musica (id_musica)
        ON DELETE CASCADE,

    CONSTRAINT ck_reproducao_segundos_ouvidos
        CHECK (segundos_ouvidos >= 0)
);

CREATE INDEX idx_reproducao_usuario
    ON reproducao (id_usuario);

CREATE INDEX idx_reproducao_musica
    ON reproducao (id_musica);

CREATE INDEX idx_reproducao_data
    ON reproducao (reproduzida_em);


-- =====================================================================
-- V9 - adicionar username e data_cadastro em usuario
-- =====================================================================
ALTER TABLE usuario
    ADD COLUMN username VARCHAR(30),
    ADD COLUMN data_cadastro TIMESTAMP WITH TIME ZONE
        NOT NULL DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE usuario
    ADD CONSTRAINT ck_usuario_username_formato
        CHECK (
            username IS NULL
            OR username ~ '^[a-z0-9._]{3,30}$'
        );

CREATE UNIQUE INDEX uk_usuario_username_ci
    ON usuario (LOWER(username))
    WHERE username IS NOT NULL;


-- =====================================================================
-- V10 - adicionar ordem e data_criacao em playlist_musica
-- =====================================================================
ALTER TABLE playlist_musica
    ADD COLUMN ordem INTEGER,
    ADD COLUMN data_criacao TIMESTAMP WITH TIME ZONE
        NOT NULL DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE playlist_musica
    ALTER COLUMN ordem SET NOT NULL;

ALTER TABLE playlist_musica
    ADD CONSTRAINT ck_playlist_musica_ordem
        CHECK (ordem > 0),

    ADD CONSTRAINT uk_playlist_musica_ordem
        UNIQUE (id_playlist, ordem);


-- =====================================================================
-- V12 - atualizar cadastro de artista (adiciona nome_completo)
-- =====================================================================
ALTER TABLE artista
    ADD COLUMN nome_completo VARCHAR(255);

ALTER TABLE artista
    ALTER COLUMN nome_completo SET NOT NULL;


-- =====================================================================
-- V13 - reforcar regras de artista (descricao obrigatoria)
-- =====================================================================
ALTER TABLE artista
    ALTER COLUMN descricao SET NOT NULL;

ALTER TABLE artista
    ADD CONSTRAINT ck_artista_descricao_nao_vazia
        CHECK (BTRIM(descricao) <> '');

ALTER TABLE artista
    ADD CONSTRAINT ck_artista_descricao_tamanho
        CHECK (CHAR_LENGTH(descricao) <= 500);


-- =====================================================================
-- V22 - expandir curadoria do perfil
-- =====================================================================
CREATE TABLE perfil_artista_favorito (
    id_perfil BIGINT NOT NULL,
    id_artista BIGINT NOT NULL,
    ordem INTEGER NOT NULL,

    CONSTRAINT pk_perfil_artista_favorito
        PRIMARY KEY (id_perfil, id_artista),
    CONSTRAINT uk_perfil_artista_favorito_ordem
        UNIQUE (id_perfil, ordem),
    CONSTRAINT fk_perfil_artista_favorito_perfil
        FOREIGN KEY (id_perfil) REFERENCES perfil (id_perfil)
        ON DELETE CASCADE,
    CONSTRAINT fk_perfil_artista_favorito_artista
        FOREIGN KEY (id_artista) REFERENCES artista (id_artista)
        ON DELETE CASCADE,
    CONSTRAINT ck_perfil_artista_favorito_ordem
        CHECK (ordem BETWEEN 0 AND 2)
);

CREATE TABLE perfil_album_favorito (
    id_perfil BIGINT NOT NULL,
    id_album BIGINT NOT NULL,
    ordem INTEGER NOT NULL,

    CONSTRAINT pk_perfil_album_favorito
        PRIMARY KEY (id_perfil, id_album),
    CONSTRAINT uk_perfil_album_favorito_ordem
        UNIQUE (id_perfil, ordem),
    CONSTRAINT fk_perfil_album_favorito_perfil
        FOREIGN KEY (id_perfil) REFERENCES perfil (id_perfil)
        ON DELETE CASCADE,
    CONSTRAINT fk_perfil_album_favorito_album
        FOREIGN KEY (id_album) REFERENCES album (id_album)
        ON DELETE CASCADE,
    CONSTRAINT ck_perfil_album_favorito_ordem
        CHECK (ordem BETWEEN 0 AND 2)
);

CREATE TABLE perfil_musica_favorita (
    id_perfil BIGINT NOT NULL,
    id_musica BIGINT NOT NULL,
    ordem INTEGER NOT NULL,

    CONSTRAINT pk_perfil_musica_favorita
        PRIMARY KEY (id_perfil, id_musica),
    CONSTRAINT uk_perfil_musica_favorita_ordem
        UNIQUE (id_perfil, ordem),
    CONSTRAINT fk_perfil_musica_favorita_perfil
        FOREIGN KEY (id_perfil) REFERENCES perfil (id_perfil)
        ON DELETE CASCADE,
    CONSTRAINT fk_perfil_musica_favorita_musica
        FOREIGN KEY (id_musica) REFERENCES musica (id_musica)
        ON DELETE CASCADE,
    CONSTRAINT ck_perfil_musica_favorita_ordem
        CHECK (ordem BETWEEN 0 AND 2)
);

CREATE INDEX idx_perfil_artista_favorito_artista
    ON perfil_artista_favorito (id_artista);
CREATE INDEX idx_perfil_album_favorito_album
    ON perfil_album_favorito (id_album);
CREATE INDEX idx_perfil_musica_favorita_musica
    ON perfil_musica_favorita (id_musica);
