sonar.projectKey=projeto-gerenciador-musica_gerenciador-musica
sonar.organization=projeto-gerenciador-musica
sonar.host.url=https://sonarcloud.io
sonar.sourceEncoding=UTF-8

sonar.sources=backend/src/main,frontend/src,scripts/povoamento,.github/workflows,backend/Dockerfile,frontend/Dockerfile,docker-compose.yml
sonar.tests=backend/src/test,frontend/src
sonar.test.inclusions=frontend/src/**/*.spec.ts
sonar.javascript.lcov.reportPaths=frontend/coverage/**/lcov.info
sonar.coverage.exclusions=scripts/povoamento/**

sonar.exclusions=frontend/src/**/*.spec.ts,frontend/node_modules/**,frontend/dist/**,backend/target/**,scripts/povoamento/dados_coletados.json

sonar.java.binaries=backend/target/classes
sonar.coverage.jacoco.xmlReportPaths=backend/target/site/jacoco/jacoco.xml
sonar.python.version=3.12