spring.application.name=gerenciador-musica-backend

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/gerenciador_musica}
spring.datasource.username=${DB_USER:gerenciador}
spring.datasource.password=${DB_PASSWORD:gerenciador_dev}

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=git 