CREATE TABLE IF NOT EXISTS artista (
    id_artista BIGINT GENERATED BY DEFAULT AS IDENTITY,
    nome VARCHAR(255) NOT NULL,
    descricao TEXT,
    foto_perfil_url VARCHAR(2048),

    CONSTRAINT pk_artista
        PRIMARY KEY (id_artista)
);



CREATE TABLE IF NOT EXISTS album (
    id_album BIGINT GENERATED BY DEFAULT AS IDENTITY,
    id_artista BIGINT NOT NULL,
    titulo VARCHAR(255) NOT NULL,
    ano_lancamento SMALLINT NOT NULL,
    capa_url VARCHAR(2048),

    CONSTRAINT pk_album
        PRIMARY KEY (id_album),

    CONSTRAINT fk_album_artista
        FOREIGN KEY (id_artista)
        REFERENCES artista (id_artista),

    CONSTRAINT ck_album_ano
        CHECK (ano_lancamento BETWEEN 1800 AND 2100)
);



CREATE TABLE IF NOT EXISTS genero (
    id_genero BIGINT GENERATED BY DEFAULT AS IDENTITY,
    nome VARCHAR(100) NOT NULL,

    CONSTRAINT pk_genero
        PRIMARY KEY (id_genero),

    CONSTRAINT uk_genero_nome
        UNIQUE (nome)
);



CREATE TABLE musica (
    id_musica BIGINT GENERATED BY DEFAULT AS IDENTITY,
    id_album BIGINT,
    titulo VARCHAR(255) NOT NULL,
    letra TEXT,
    duracao_segundos INTEGER NOT NULL,
    ano_lancamento SMALLINT NOT NULL,

    CONSTRAINT pk_musica
        PRIMARY KEY (id_musica),

    CONSTRAINT fk_musica_album
        FOREIGN KEY (id_album)
        REFERENCES album (id_album),

    CONSTRAINT ck_musica_duracao
        CHECK (duracao_segundos > 0),

    CONSTRAINT ck_musica_ano
        CHECK (ano_lancamento BETWEEN 1800 AND 2100)
);



CREATE TABLE IF NOT EXISTS musica_artista (
    id_musica BIGINT NOT NULL,
    id_artista BIGINT NOT NULL,

    CONSTRAINT pk_musica_artista
        PRIMARY KEY (id_musica, id_artista),

    CONSTRAINT fk_musica_artista_musica
        FOREIGN KEY (id_musica)
        REFERENCES musica (id_musica)
        ON DELETE CASCADE,

    CONSTRAINT fk_musica_artista_artista
        FOREIGN KEY (id_artista)
        REFERENCES artista (id_artista)
        ON DELETE CASCADE
);



CREATE TABLE IF NOT EXISTS musica_genero (
    id_musica BIGINT NOT NULL,
    id_genero BIGINT NOT NULL,

    CONSTRAINT pk_musica_genero
        PRIMARY KEY (id_musica, id_genero),

    CONSTRAINT fk_musica_genero_musica
        FOREIGN KEY (id_musica)
        REFERENCES musica (id_musica)
        ON DELETE CASCADE,

    CONSTRAINT fk_musica_genero_genero
        FOREIGN KEY (id_genero)
        REFERENCES genero (id_genero)
        ON DELETE CASCADE
);

