CREATE TABLE IF NOT EXISTS playlist (
    id_playlist BIGINT GENERATED BY DEFAULT AS IDENTITY,
    nome VARCHAR(255) NOT NULL,
    descricao TEXT,
    id_usuario BIGINT NOT NULL,
    data_criacao TIMESTAMP WITH TIME ZONE
        NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT pk_playlist
        PRIMARY KEY (id_playlist),

    CONSTRAINT fk_playlist_usuario
        FOREIGN KEY (id_usuario)
        REFERENCES usuario (id)
        ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS playlist_musica (
    id_playlist BIGINT NOT NULL,
    id_musica BIGINT NOT NULL,

    CONSTRAINT pk_playlist_musica
        PRIMARY KEY (id_playlist, id_musica),

    CONSTRAINT fk_playlist_musica_playlist
        FOREIGN KEY (id_playlist)
        REFERENCES playlist (id_playlist)
        ON DELETE CASCADE,

    CONSTRAINT fk_playlist_musica_musica
        FOREIGN KEY (id_musica)
        REFERENCES musica (id_musica)
        ON DELETE CASCADE
);