CREATE TABLE perfil (
    id_perfil BIGINT GENERATED BY DEFAULT AS IDENTITY,
    id_usuario BIGINT NOT NULL,

    foto_url VARCHAR(2048),
    banner_url VARCHAR(2048),
    biografia TEXT,
    frase_destaque VARCHAR(500),

    id_artista_destaque BIGINT,
    id_album_destaque BIGINT,
    id_musica_destaque BIGINT,

    CONSTRAINT pk_perfil
        PRIMARY KEY (id_perfil),

    CONSTRAINT uk_perfil_usuario
        UNIQUE (id_usuario),

    CONSTRAINT fk_perfil_usuario
        FOREIGN KEY (id_usuario)
        REFERENCES usuario (id)
        ON DELETE CASCADE,

    CONSTRAINT fk_perfil_artista_destaque
        FOREIGN KEY (id_artista_destaque)
        REFERENCES artista (id_artista)
        ON DELETE SET NULL,

    CONSTRAINT fk_perfil_album_destaque
        FOREIGN KEY (id_album_destaque)
        REFERENCES album (id_album)
        ON DELETE SET NULL,

    CONSTRAINT fk_perfil_musica_destaque
        FOREIGN KEY (id_musica_destaque)
        REFERENCES musica (id_musica)
        ON DELETE SET NULL
);

CREATE INDEX idx_perfil_artista_destaque
    ON perfil (id_artista_destaque);

CREATE INDEX idx_perfil_album_destaque
    ON perfil (id_album_destaque);

CREATE INDEX idx_perfil_musica_destaque
    ON perfil (id_musica_destaque);