CREATE TABLE review (
    id_review BIGINT GENERATED BY DEFAULT AS IDENTITY,
    id_usuario BIGINT NOT NULL,
    id_musica BIGINT NOT NULL,
    nota SMALLINT NOT NULL,
    texto TEXT,
    criada_em TIMESTAMP WITH TIME ZONE
        NOT NULL DEFAULT CURRENT_TIMESTAMP,
    atualizada_em TIMESTAMP WITH TIME ZONE
        NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT pk_review
        PRIMARY KEY (id_review),

    CONSTRAINT fk_review_usuario
        FOREIGN KEY (id_usuario)
        REFERENCES usuario (id)
        ON DELETE CASCADE,

    CONSTRAINT fk_review_musica
        FOREIGN KEY (id_musica)
        REFERENCES musica (id_musica)
        ON DELETE CASCADE,

    CONSTRAINT uk_review_usuario_musica
        UNIQUE (id_usuario, id_musica),

    CONSTRAINT ck_review_nota
        CHECK (nota BETWEEN 1 AND 5),

    CONSTRAINT ck_review_texto
        CHECK (texto IS NULL OR BTRIM(texto) <> '')
);

CREATE INDEX idx_review_musica
    ON review (id_musica);

CREATE INDEX idx_review_usuario
    ON review (id_usuario);

CREATE OR REPLACE FUNCTION fn_atualizar_data_review()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
    NEW.atualizada_em = CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$;

CREATE TRIGGER trg_atualizar_data_review
BEFORE UPDATE ON review
FOR EACH ROW
EXECUTE FUNCTION fn_atualizar_data_review();