CREATE TABLE curtida_musica (
    id_usuario BIGINT NOT NULL,
    id_musica BIGINT NOT NULL,
    curtida_em TIMESTAMP WITH TIME ZONE
        NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT pk_curtida_musica
        PRIMARY KEY (id_usuario, id_musica),

    CONSTRAINT fk_curtida_musica_usuario
        FOREIGN KEY (id_usuario)
        REFERENCES usuario (id)
        ON DELETE CASCADE,

    CONSTRAINT fk_curtida_musica_musica
        FOREIGN KEY (id_musica)
        REFERENCES musica (id_musica)
        ON DELETE CASCADE
);

CREATE INDEX idx_curtida_musica_musica
    ON curtida_musica (id_musica);


CREATE TABLE reproducao (
    id_reproducao BIGINT GENERATED BY DEFAULT AS IDENTITY,
    id_usuario BIGINT NOT NULL,
    id_musica BIGINT NOT NULL,
    reproduzida_em TIMESTAMP WITH TIME ZONE
        NOT NULL DEFAULT CURRENT_TIMESTAMP,
    segundos_ouvidos INTEGER NOT NULL,

    CONSTRAINT pk_reproducao
        PRIMARY KEY (id_reproducao),

    CONSTRAINT fk_reproducao_usuario
        FOREIGN KEY (id_usuario)
        REFERENCES usuario (id)
        ON DELETE CASCADE,

    CONSTRAINT fk_reproducao_musica
        FOREIGN KEY (id_musica)
        REFERENCES musica (id_musica)
        ON DELETE CASCADE,

    CONSTRAINT ck_reproducao_segundos_ouvidos
        CHECK (segundos_ouvidos >= 0)
);

CREATE INDEX idx_reproducao_usuario
    ON reproducao (id_usuario);

CREATE INDEX idx_reproducao_musica
    ON reproducao (id_musica);

CREATE INDEX idx_reproducao_data
    ON reproducao (reproduzida_em);